### ISSUE TITLE
Session recovery on re-connect

### ISSUE THREAD

**Issue by h3** [andrewgodwin/channels#271] opened 2016-07-26 19:00 UTC
Consider a frontend connected to the backend via websockets and the backend goes down for a couple of seconds.

The frontend can detect the disconnect and start trying to reconnect, that part is cake.

However when the websocket connection is re-established, the session is gone. From what I understand, this occurs because the session is piggy backed on the HTTP request, which does not happen with subsequent socket connections.

So, is there anyway to recover a websocket connection *with* its session ? Or it's gone for good as soon as the socket is closed ?

I did not find much in the documentation about this situation..

Regards

**Comment by andrewgodwin** [comment] 2016-07-26 19:28
If you have a HTTP session with cookies, every WebSocket connection should inherit this on connection - however, that is only available at connection time, and during message receive you just have the channel session (so you do not have access to the HTTP session to write any more unless you manually persisted the key into the channel session).

We could potentially bridge the HTTP session across into receives via the channel session. What are you persisting that you wish to keep track of?

**Comment by h3** [comment] 2016-07-26 20:03
Principally informations related to the state of the application, things that change too often and are too ephemeral to be in the DB but needs to be persisted as long as the user is logged in.

My biggest problem is that when I reconnect a dropped socket without reloading the page, message.user becomes AnonymousUser as if the user is not authenticated.

If I do a page reload, the HTTP session still see the user as authenticated and message.user start returning the correct user again on the consumer side.. but without its session data.

My main concern is when deploying updates, the backend is reloaded and thus drops active connections. 

It wouldn't be a concern if the frontend could restore the connections automatically after.

**Comment by andrewgodwin** [comment] 2016-07-27 09:25
You're saying that when your socket reconnects it doesn't re-authenticate the same? That's a bug, since it's definitely intended to and it does on my system when I tried it just now.

A few questions:
* What session backend are you using?
* What websocket reconnection logic are you using?
* Does this happen with `runserver`, in a production environment, or both?

**Comment by h3** [comment] 2016-07-27 12:26
1. I did not change de default session backend (database)
2. See below
3. Both

Here's the javascript logic, sorry some of it is pseudo code, I had to scrub it..

This is a wrapper:

```javascript

var WsHandler = function(){
  var $self = this;
  var ws = window.location.protocol == 'https:' ? 'wss' : 'ws';
  $self.callbacks = [];

  $self.invokeCallback = function(e, payload) {
    for (var i = 0; i < $self.callbacks.length; i++) {
      var cb = $self.callbacks[i];
      if (cb.eventName == payload.eventName) {
        cb.callback(e, payload);
      }
    }
  };

  $self.connect = function() {
    $self.socket = new WebSocket(ws + '://' + window.location.host + '/');
    $self.socket.onopen = function(e) {
      $self.ready = true;
      $self.invokeCallback(e, {eventName: 'connected', data: {}})
    };

    $self.socket.onclose = function(e) {
      $self.ready = false;
      $self.invokeCallback(e, {eventName: 'disconnected', data: {}})
    };

    $self.socket.onerror = function(e) {
      $self.ready = false;
      $self.invokeCallback(e, {eventName: 'error', data: e})
    };

    $self.socket.onmessage = function(e) {
      var payload = JSON.parse(e.data);
      $self.invokeCallback(e, payload);
    };
  };

  $self.connect();

  return {
    ws: $self.socket,
    connect: function() {
      if (!$self.ready) {
        $self.connect();
      }
    },
    send: function(j) {
      if (!$self.ready) {
        $self.connect();
      }
      $self.socket.send(JSON.stringify(j));
    },
    on: function(eventName, callback){
      $self.callbacks.push({eventName: eventName, callback: callback});
    }
  }

};
```

This is how the frontend uses the above wrapper:


```javascript
var ws = new WsHandler();

ws.on('ready', function(e, resp){
   ws.send({command: 'some-command', data: state});
});

// Reconnect logic

ws.on('disconnected',  function(e, resp){
  instance.ready = false;
  setTimeout(function(){
      ws.connect();
  }, 5000);
});
```

And these are the consumers:

```python
@retry_on_db_error
@channel_session_user_from_http
def ws_on_connect(message):
    ip, port = message.content.get('client')
    headers = dict(message.get('headers'))
    # Account for reverse proxies
    if 'x-forwarded-for' in headers.keys():
        ip = headers.get('x-forwarded-for')
    elif 'x-real-ip' in headers.keys():
        ip = headers.get('x-real-ip')
    message.channel_session['REMOTE_ADDR'] = ip
    message.reply_channel.send({'text': json.dumps({
        'eventName': 'ready', 'data': {}
    })})



@retry_on_db_error
@channel_session_user
def ws_on_message(message):
    payload = json.loads(message['text'])
    message.channel_session['state'] = payload['state']

    allowed_actions = get_allowed_actions_for_user(message.user)

    if payload['command'] == 'some-command':
        message.reply_channel.send({'text': json.dumps({
          'eventName': 'completed',
          'data': some_command_output(),
        })})

@retry_on_db_error
@channel_session_user
def ws_on_disconnect(message):
    message.reply_channel.send({
        'text': json.dumps({"command": 'disconnect'})
    })
```

Note: the `@retry_on_db_error` is a decorator to workaround the MySQL connection timeout.

This is the code, just in case:

```python
def retry_on_db_error(f):
    """
    https://github.com/andrewgodwin/channels/issues/148
    """
    @functools.wraps(f)
    def decorated_function(*args, **kwargs):
        try:
            return f(*args, **kwargs)
        except db.utils.OperationalError as e:
            db.connection.close()
            return f(*args, **kwargs)
    return decorated_function
```

**Comment by andrewgodwin** [comment] 2016-07-27 13:07
That all looks about right, I don't know why it's not preserving the user on the second connect - can you get the connect handler to print out the headers and make sure you're still getting a cookie sent across the second time?

Also, are you running current versions of `daphne`, `channels`, `asgi_redis` and `asgiref`? The DB error from issue #148 was fixed several releases ago, so you shouldn't need the decorator any more.

**Comment by h3** [comment] 2016-07-27 14:34
* channels: 0.14.2
* daphne: 0.12.1
* asgi_redis: 0.13.1
* asgiref: 0.13.3

From my tests it seems the sessions do get passed correctly to `ws_on_connect`:

Headers for initial connection:

```javascript
{
  'origin': 'http://127.0.0.1:8000',
  'upgrade': 'websocket',
  'accept-language': 'en-GB,en-US;q=0.8,en;q=0.6',
  'accept-encoding': 'gzip, deflate, sdch',
  'sec-websocket-version': '13',
  'connection': 'Upgrade',
  'sec-websocket-key': '0ag42bDRE9xHzfegKPOA+A==',
  'user-agent': 'Mozilla/5.0 ...',
  'host': '127.0.0.1:8000',
  'cookie': 'sessionid=a28xonfrvlvtd5rht1takaa3vjl718p8; csrftoken=yLi3Lop9oGlwIDXsN8ZgBOT9XZ8U90KA',
  'pragma': 'no-cache',
  'cache-control': 'no-cache',
  'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'
}
```

Headers of reconnection:

```javascript
{
  'origin': 'http://127.0.0.1:8000',
  'upgrade': 'websocket',
  'accept-language': 'en-GB,en-US;q=0.8,en;q=0.6',
  'accept-encoding': 'gzip, deflate, sdch',
  'sec-websocket-version': '13',
  'connection': 'Upgrade',
  'sec-websocket-key': 'l8SvaoB65MX45R8Rr1NW0w==',
  'user-agent': 'Mozilla/5.0 ...',
  'host': '127.0.0.1:8000',
  'cookie': 'sessionid=a28xonfrvlvtd5rht1takaa3vjl718p8; csrftoken=yLi3Lop9oGlwIDXsN8ZgBOT9XZ8U90KA',
  'pragma': 'no-cache',
  'cache-control': 'no-cache',
  'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'
}
```

And indeed the message.user and session data is correct even after a reconnect.

The problem seems limited to `ws_on_message` which receive the user and session data on
first connection, but not upon after a reconnection.

**Comment by h3** [comment] 2016-07-27 15:09
I'm sorry I was wrong.

After a socket reconnect `ws_on_connect` indeed recovers the user session, but not the state data I attached to the session while `ws_on_message` lose the user _and_ the state data.

**Comment by h3** [comment] 2016-07-27 18:31
I managed to workaround part of the problem while trying to reproduce inside a blank project. 

From the frontend I listen for socket connection, unpon which I ask the backend to return me the current user.

Now it seems that if the frontend make this request too fast after the connection event, the backend returns either AnonymousUser or the correct user .. totally randomly.

But if I wrap this call in a setTimeout and make it wait a little, it always return the correct user.

That said, like in my project, the session data is always lost between disconnects/reconnects.

I pushed the test project on github: https://github.com/h3/channels-issue-271

Running the script `./start` will bootstrap the project inside a virtualenv and run it (on port 8888).

Use the user **demo** with password **helloworld** to log in.

After you log in, wait a couple of seconds, kill the backend and relaunch it.

Note: if you want to see the random user returned behavior, just remove the setTimeout [around this line](https://github.com/h3/channels-issue-271/blob/master/testapp/static/testapp/js/main.js#L10).

Thanks

**Comment by andrewgodwin** [comment] 2016-07-27 18:33
Ah, have you tried using the `enforce_ordering` decorator? http://channels.readthedocs.io/en/latest/getting-started.html#enforcing-ordering

It sounds like you have a race condition, and by using that in non-strict mode you should guarantee that connect finishes before receive starts.

**Comment by h3** [comment] 2016-07-27 18:48
Indeed, the `enforce_ordering` seems to resolve the concurrency issue with message.user.

However I still have the session dropped after reconnect problem..

I've committed the change to the test project.

**Comment by h3** [comment] 2016-07-27 18:56
I've updated the test project to use the latest channels commit just to be sure, problem still there.

**Comment by andrewgodwin** [comment] 2016-07-28 09:54
So, to get this clear, does `message.user` now always work, or is it part of the session dropped after reconnect problem? I'm not sure what exactly enforce_ordering fixed for you and what it didn't.

**Comment by h3** [comment] 2016-07-28 12:50
Take this for example: https://github.com/h3/channels-issue-271/blob/master/testapp/consumers.py

At some point the `ws_on_message` consumer sets a "state" variable in session:

```python
message.channel_session['state'] = payload['data']
```

As long as the socket stays alive `ws_on_message` is able to retrieve the value of `message.channel_session['state']`.

But if the backend is restarted, the value of `message.channel_session['state']` vanish.

At first it was also the case for `message.user`, but `enforce_ordering` fixed that.

Maybe it's something I don't understand about session ?

**Comment by andrewgodwin** [comment] 2016-07-28 16:45
Ahhh! The `channel_session` is only valid for the lifetime for that one socket connection - when the socket drops and reconnects, it's a new socket, so you get a new `channel_session`. The behaviour you're seeing is exactly as designed.

Now, there's potential for us to somehow bridge the `http_session` across into other receivers - I presume that's what you want? (the `http_session` is the session object that the user has on the rest of the site, and that you'd see as `request.session` on HTTP views)

**Comment by h3** [comment] 2016-07-28 16:57
OK, I wasn't sure if it was by design.

In my case it's not dramatic because the frontend still has the data and can push it back once it reconnect.

But I would certainly find it useful to be able to access the http_session from the receivers.

Thanks a lot for you help, it's really appreciated.

**Comment by andrewgodwin** [comment] 2016-08-26 04:51
Closing this and opening a new ticket with the task to be done.

**Closed by andrewgodwin** 2016-08-26 04:51 UTC
Labels: blocked/user-response, enhancement
