### ISSUE TITLE
Feature request: Group size.

### ISSUE THREAD

**Issue by Zapix** [andrewgodwin/channels#187] opened 2016-06-02 08:03 UTC
Hi. 

It could be useful to track size on group. to tracking online/offline users for example or remove chat if all users disconnected. I think we could add `group_size` method to `ChannelLayer` and `__len__` magic method to `Group`. Also it shouldn't be a problem to implement it in  inmemory and redis channel layers.

**Comment by andrewgodwin** [comment] 2016-06-03 00:01
I'm going to close this as a dupe of #174, as that fulfills a very similar contract and the solution will be either list-of-channels or number-of-channels.

**Closed by andrewgodwin** 2016-06-03 00:01 UTC
