### ISSUE TITLE
Generic consumers not authenticating users

### ISSUE THREAD

**Issue by pydanny** [andrewgodwin/channels#243] opened 2016-07-12 16:34 UTC
Even when authenticated, the user attached to the incoming message is always an `AnonymousUser`.

My specs:

* Python 3.5
* Django 1.9.7
* Channels 0.16.0
* Redis backend
* OSX 10.10.5
* Chrome 51.x
* reconnecting-websocket for connecting from browser to client

My routes:

``` python
from channels.routing import route_class

from . import consumers

channel_routing = [
    route_class(consumers.DiscussionConsumerServer, path=r"^/"),
]
```

My consumer:
``` python
from channels.generic.websockets import JsonWebsocketConsumer

class DiscussionConsumerServer(JsonWebsocketConsumer):

    channel_session_user = True

    def connect(self, message, **kwargs):
        """
        Perform things on connection start
        """
        if message.user.is_anonymous():
            raise Exception("user is anonymous")
```

**Comment by andrewgodwin** [comment] 2016-07-12 16:41
Duplicate of #221. I should be looking at this today.

**Closed by andrewgodwin** 2016-07-12 16:41 UTC
