### ISSUE TITLE
Worker silently died if content is not under ASGI spec

### ISSUE THREAD

**Issue by Skorpyon** [andrewgodwin/channels#290] opened 2016-08-10 05:22 UTC
I made wrong API call:
```python
Channel('websocket.send!EPEdqynkLZYP')\
.send({"text": {'message': 'bot message', 'msg_type': 0, 'username': 'BOT'}})
```
'text' key value should be a string, not a dict, right, but..

Not rising error, nothing happen, only worker doesn't listen HTTP requests and response with
> ### 503 Service Unavailable
> Worker server failed to respond within time limit.
> #### Daphne

**Comment by andrewgodwin** [comment] 2016-08-11 04:52
This is a duplicate of #289 - fix will be released soon.

**Closed by andrewgodwin** 2016-08-11 04:52 UTC
