### ISSUE TITLE
What is the best way to push dict from server ?

### ISSUE THREAD

**Issue by rajasimon** [andrewgodwin/channels#68] opened 2016-01-14 14:01 UTC
Hi... Currently I'm doing this.. I need more efficient way to pass dict and get it from frontend .. thanks 

In my django views file I have this 

    messenger['content'] = '{' + '"name" :"{}", "ip_address" :"{}"'.format(name, ip_address) + '}'
    result['message'] = "Ip Address associated with {} deleted".format(name)
    Group("chat").send(messenger) 

And in the html I have this to parse the string ...

    var result = JSON.parse(e.data);
    console.log(result);

So I guess this is not the correct way. Then what is the good way ?

**Comment by rollokb** [comment] 2016-01-14 15:22
What's wrong with parsing JSON?

**Comment by andrewgodwin** [comment] 2016-01-14 18:05
Yes, that's entirely normal; data needs some kind of serialisation over the wire; you could make life easier by using the `json` module in Python to encode things, though.

Closing as it's not a bug in Channels.

**Closed by andrewgodwin** 2016-01-14 18:05 UTC
